[[websites]]
name ="Example 1 Site"
slug = "Example1"
about = "Example Website 1!"
url = "https://example1.com"
owner = "owner 1"

[[websites]]
name = "Example 2 Site"
slug = "Example2"
about = "Example Website 2!"
url = "https://example2.com"
rss = "https://example2.com/index.xml"
owner = "owner 2"

[[websites]]
name = "Example 3 Site"
slug = "Example3"
about = "Example Website 3!"
url = "https://example3.com"
rss = "https://example.3com/rss/index.xml"
owner = "owner 3"

[[websites]]
name = "Example 4 Site"
slug = "Example4"
about = "Example Website 4!"
url = "https://example4.com"
owner = "owner 4"

[[websites]]
name = "Example 5 Site"
slug = "Example5"
about = "Example Website 5!"
url = "https://example5.com"
owner = "owner 5"

