name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable
      
    - name: Build
      run: cargo build --release
      
    - name: Run Tests
      run: cargo test --all